name = "EnochBlogTheme"
license = "MIT"
licenselink = "https://github.com/enochyu-official/EnochBlogTheme/blob/main/LICENSE"
description = "Simple and elegant Hugo blog theme."
homepage = "https://github.com/enochyu-official/EnochBlogTheme"
demosite = "https://blog.enochyu.com/"

tags = ["blog", "elegant", "responsive", "minimal" ]
features = [
    "sidebar",
    "toc",
    "giscus",
    "search",
]

[author]
name = "Enoch Yu"
homepage = "https://enochyu.com/"
