name = "EnochBlogTheme"
license = "MIT"
licenselink = "https://github.com/enochyu-official/EnochBlogTheme/blob/master/LICENSE"
description = "A Hugo blog theme with glassmorphism and Bootstrap"
homepage = "https://github.com/enochyu-official/EnochBlogTheme"
# demosite = ""

tags = ["blog", "glassmorphism", "bootstrap", "responsive", "minimal" ]
features = [
    "widgets",
    "sidebar",
    "toc",
    "giscus",
    "darkmode",
    "search",
]

[author]
name = "Enoch Yu"
# homepage = ""
